version: "3"
services:
  ollama:
    image: jianshao/ollama-server:${image_ver}
    container_name: ${container_name_prefix}ollama
    restart: unless-stopped
    volumes:
      - ${model_cache_path}:/home/devel/.ollama
    ports:
      - 11434:11434
  nextchat:
    image: yidadaa/chatgpt-next-web:v2.14.1
    container_name: ${container_name_prefix}nextchat
    restart: unless-stopped
    depends_on:
      - ollama
    environment:
      - BASE_URL=http://ollama:11434
    ports:
      - 3000:3000
